version: '2'
services:
  web:
    environment:
      PEPIS_CMS_DATABASE_CONFIG_TYPE: native
      PEPIS_CMS_DATABASE_HOSTNAME: db
      PEPIS_CMS_DATABASE_USERNAME: pepiscms
      PEPIS_CMS_DATABASE_PASSWORD: pepiscms
      PEPIS_CMS_DATABASE_DATABASE: pepiscms
      PEPIS_CMS_AUTH_DRIVER: native
      PEPIS_CMS_AUTH_EMAIL: demo@example.com
      PEPIS_CMS_AUTH_PASSWORD: demodemo
      PEPIS_CMS_SITE_EMAIL: demo@example.com
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./app:/app
    build: ./docker/web/
    command: /install.sh

  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pepiscms
      MYSQL_PASSWORD: pepiscms
      MYSQL_DATABASE: pepiscms
    ports:
      - "3309:3306"